"""login_states + cluster_locks for multi-worker safety

Revision ID: 452a8650bcf0
Revises: 5dd55d301527
Create Date: 2026-07-29 04:33:01.492519
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '452a8650bcf0'
down_revision: Union[str, None] = '5dd55d301527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_locks',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('login_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    with op.batch_alter_table('login_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_states_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_states_expires_at'))

    op.drop_table('login_states')
    op.drop_table('cluster_locks')
    # ### end Alembic commands ###
