"""platform key defaults

Revision ID: 453f0fe9fef9
Revises: f2493af2c863
Create Date: 2026-07-29 22:22:44.121398
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '453f0fe9fef9'
down_revision: Union[str, None] = 'f2493af2c863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_config', schema=None) as batch_op:
        # server_default so the column can be added to a table that already has
        # the singleton config row — without it this fails on any live panel.
        batch_op.add_column(sa.Column(
            'default_key_assignments', sa.JSON(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_config', schema=None) as batch_op:
        batch_op.drop_column('default_key_assignments')

    # ### end Alembic commands ###
