"""baseline: full control-plane schema

Revision ID: 5dd55d301527
Revises: 
Create Date: 2026-07-29 04:15:33.066149
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5dd55d301527'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=True),
    sa.Column('tenant_slug', sa.String(length=63), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_anchors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('head', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_anchors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_anchors_created_at'), ['created_at'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('federation_config',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('groups_claim', sa.String(length=80), nullable=False),
    sa.Column('group_role_map', sa.JSON(), nullable=False),
    sa.Column('default_role', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_config',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('platform_name', sa.String(length=120), nullable=True),
    sa.Column('tagline', sa.String(length=160), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=9), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('org_legal_name', sa.String(length=255), nullable=True),
    sa.Column('org_type', sa.String(length=32), nullable=False),
    sa.Column('jurisdiction', sa.String(length=160), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('boundary', sa.JSON(), nullable=True),
    sa.Column('boundary_label', sa.String(length=255), nullable=True),
    sa.Column('retention_state_code', sa.String(length=2), nullable=False),
    sa.Column('retention_days_override', sa.Integer(), nullable=True),
    sa.Column('retention_mode', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('releases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('backend_image', sa.String(length=255), nullable=False),
    sa.Column('frontend_image', sa.String(length=255), nullable=False),
    sa.Column('backend_digest', sa.String(length=80), nullable=True),
    sa.Column('frontend_digest', sa.String(length=80), nullable=True),
    sa.Column('db_revision', sa.String(length=64), nullable=True),
    sa.Column('min_db_revision', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('service_categories',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('group', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('state_credentials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('key_name', sa.String(length=128), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('state_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_credentials_key_name'), ['key_name'], unique=True)

    op.create_table('system_settings',
    sa.Column('key_name', sa.String(length=128), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key_name')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('contact_title', sa.String(length=128), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('boundary', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('county', sa.String(length=120), nullable=True),
    sa.Column('managed_settings', sa.JSON(), nullable=False),
    sa.Column('key_assignments', sa.JSON(), nullable=False),
    sa.Column('running_version', sa.String(length=64), nullable=True),
    sa.Column('target_version', sa.String(length=64), nullable=True),
    sa.Column('db_name', sa.String(length=63), nullable=True),
    sa.Column('kms_key_ref', sa.String(length=255), nullable=True),
    sa.Column('storage_bucket', sa.String(length=255), nullable=True),
    sa.Column('backend_port', sa.Integer(), nullable=True),
    sa.Column('frontend_port', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenants_status'), ['status'], unique=False)

    op.create_table('town_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ref_code', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('requested_slug', sa.String(length=63), nullable=True),
    sa.Column('county', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('key_preferences', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_code')
    )
    with op.batch_alter_table('town_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_town_requests_status'), ['status'], unique=False)

    op.create_table('uptime_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uptime_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uptime_records_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uptime_records_service_name'), ['service_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('oidc_sub', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oidc_sub')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('backup_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('category_mappings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('local_key', sa.String(length=160), nullable=False),
    sa.Column('canonical_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'local_key')
    )
    with op.batch_alter_table('category_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_mappings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('platform_secrets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('key_name', sa.String(length=128), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key_name')
    )
    with op.batch_alter_table('platform_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_secrets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('provision_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('onboarding_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provision_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provision_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('rollouts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('release_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('canary_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_snapshots_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('provision_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['provision_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provision_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provision_steps_job_id'), ['job_id'], unique=False)

    op.create_table('rollout_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rollout_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('previous_version', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rollout_id'], ['rollouts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rollout_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rollout_steps_rollout_id'), ['rollout_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollout_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollout_steps_rollout_id'))

    op.drop_table('rollout_steps')
    with op.batch_alter_table('provision_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provision_steps_job_id'))

    op.drop_table('provision_steps')
    with op.batch_alter_table('telemetry_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_snapshots_tenant_id'))

    op.drop_table('telemetry_snapshots')
    op.drop_table('rollouts')
    with op.batch_alter_table('provision_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provision_jobs_tenant_id'))

    op.drop_table('provision_jobs')
    with op.batch_alter_table('platform_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_secrets_tenant_id'))

    op.drop_table('platform_secrets')
    with op.batch_alter_table('category_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_mappings_tenant_id'))

    op.drop_table('category_mappings')
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_backup_records_created_at'))

    op.drop_table('backup_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('uptime_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uptime_records_service_name'))
        batch_op.drop_index(batch_op.f('ix_uptime_records_checked_at'))

    op.drop_table('uptime_records')
    with op.batch_alter_table('town_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_town_requests_status'))

    op.drop_table('town_requests')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_status'))
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))
        batch_op.drop_index(batch_op.f('ix_tenants_county'))

    op.drop_table('tenants')
    op.drop_table('system_settings')
    with op.batch_alter_table('state_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_credentials_key_name'))

    op.drop_table('state_credentials')
    op.drop_table('service_categories')
    op.drop_table('releases')
    op.drop_table('platform_config')
    op.drop_table('federation_config')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_seq'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('audit_anchors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_anchors_created_at'))

    op.drop_table('audit_anchors')
    op.drop_table('announcements')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_kind'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
