"""upstream candidates

Revision ID: f2493af2c863
Revises: 452a8650bcf0
Create Date: 2026-07-29 05:59:08.299147
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f2493af2c863'
down_revision: Union[str, None] = '452a8650bcf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upstream_candidates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('backend_digest', sa.String(length=80), nullable=False),
    sa.Column('frontend_digest', sa.String(length=80), nullable=False),
    sa.Column('backend_image', sa.String(length=255), nullable=False),
    sa.Column('frontend_image', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=True),
    sa.Column('db_revision', sa.String(length=64), nullable=True),
    sa.Column('min_db_revision', sa.String(length=64), nullable=True),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('signature_detail', sa.Text(), nullable=True),
    sa.Column('stamp_complete', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('release_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upstream_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upstream_candidates_backend_digest'), ['backend_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_upstream_candidates_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upstream_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upstream_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_upstream_candidates_backend_digest'))

    op.drop_table('upstream_candidates')
    # ### end Alembic commands ###
